### ISSUE TITLE
GUI hatası

### ISSUE THREAD

**Issue by sercankavdir** [sercankavdir/ieuRef-V2#1]
Verileri .bib uzantısından aldıktan sonra IDE arayüzünde kolaylıkla (author,title,year vs) print edebiliyoruz. Ancak arayüze bir türlü aktaramıyoruz.

**Comment by Schacher** [comment]
Benim eklediğim kısımdaki printleri çalıştırıp, GUI ye aktarma kısmını inceleyebilirsiniz arkadaşlar...

**Comment by Schacher** [comment]
Sorun çözüldü basit bir kod kullanmamız gerekliymiş.
